# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-android/ for more details
#
version: 2.1

jobs:

  build:

    working_directory: ~/Abbey

    docker:
      - image: circleci/android:api-29

    steps:
      - checkout

      - restore_cache:
          keys:
            - abbey-dependencies-{{ checksum "build.gradle" }}
            - abbey-dependencies-

      - run:
          name: Assemble
          command: ./gradlew assembleDebug

      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - save_cache:
          paths:
            - ~/.gradle
          key: abbey-dependencies-{{ checksum "build.gradle" }}
